branch-defaults:
  default:
    environment: capstone-env
  register:
    environment: flask-env
    group_suffix: null
environment-defaults:
  capstone-env:
    branch: null
    repository: null
global:
  application_name: capstone-app
  branch: null
  default_ec2_keyname: capstone2021
  default_platform: Python 3.7
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
